const mongoose = require("mongoose");

const ArtworkSchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: { type: String, required: true },
  price: { type: Number, required: true },
  category: { type: String, required: true },
  imageUrl: { type: String, required: true }, // The url generated by imgBB
  artist: {
    name: { type: String, default: "Aria Nakamura" }, // Temporarily hardcoded until auth is set up
    email: { type: String, default: "aria@arthub.com" }
  },
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model("Artwork", ArtworkSchema);